[project]
name = "mcp_dynamodb"
version = "0.1.0"
description = "DynamoDB MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore>=0.1.5",
    "fastmcp>=2.12.3",
    "opentelemetry-api>=1.37.0",
    "opentelemetry-sdk>=1.37.0",
]
